// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: errorCode.proto

package errCode

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Code int32

const (
	Code_ok                  Code = 0
	Code_typeNoMatch         Code = 1 //类型不匹配
	Code_moduleRegistErr     Code = 2 //模块注册失败
	Code_noFindModuleForTask Code = 3 //没有找到可执行任务的模块
	Code_noAuthority         Code = 4 //权限不足
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "ok",
		1: "typeNoMatch",
		2: "moduleRegistErr",
		3: "noFindModuleForTask",
		4: "noAuthority",
	}
	Code_value = map[string]int32{
		"ok":                  0,
		"typeNoMatch":         1,
		"moduleRegistErr":     2,
		"noFindModuleForTask": 3,
		"noAuthority":         4,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_errorCode_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_errorCode_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_errorCode_proto_rawDescGZIP(), []int{0}
}

var File_errorCode_proto protoreflect.FileDescriptor

var file_errorCode_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x2a, 0x5e, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x6f, 0x6b, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x74, 0x79,
	0x70, 0x65, 0x4e, 0x6f, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x6d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x45, 0x72, 0x72, 0x10, 0x02,
	0x12, 0x17, 0x0a, 0x13, 0x6e, 0x6f, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x46, 0x6f, 0x72, 0x54, 0x61, 0x73, 0x6b, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x6e, 0x6f, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x10, 0x04, 0x42, 0x1a, 0x5a, 0x18, 0x6a, 0x34,
	0x66, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x3b, 0x65,
	0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_errorCode_proto_rawDescOnce sync.Once
	file_errorCode_proto_rawDescData = file_errorCode_proto_rawDesc
)

func file_errorCode_proto_rawDescGZIP() []byte {
	file_errorCode_proto_rawDescOnce.Do(func() {
		file_errorCode_proto_rawDescData = protoimpl.X.CompressGZIP(file_errorCode_proto_rawDescData)
	})
	return file_errorCode_proto_rawDescData
}

var file_errorCode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errorCode_proto_goTypes = []interface{}{
	(Code)(0), // 0: errCode.code
}
var file_errorCode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errorCode_proto_init() }
func file_errorCode_proto_init() {
	if File_errorCode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_errorCode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errorCode_proto_goTypes,
		DependencyIndexes: file_errorCode_proto_depIdxs,
		EnumInfos:         file_errorCode_proto_enumTypes,
	}.Build()
	File_errorCode_proto = out.File
	file_errorCode_proto_rawDesc = nil
	file_errorCode_proto_goTypes = nil
	file_errorCode_proto_depIdxs = nil
}
